package-lock.json, package.json, script/seed.js, server/db/models/address.js, server/db/models/cart.js, server/db/models/category.js, server/db/models/country.js, server/db/models/index.js, server/db/models/merchant.js, server/db/models/order.js, server/db/models/order_item.js, server/db/models/product.js, server/db/models/review.js, server/db/models/user.js
=> Sequelize models

script/seed.js, server/db/models/cart_item.js, server/db/models/index.js, server/db/models/order_item.js
=> updated cart items and order items to be join tables

server/api/cart.js, server/api/index.js, server/api/product.js, server/db/models/index.js, server/db/models/review.js
=> Api routes

client/components/auth-form.js, client/components/catalog.js, client/components/index.js, client/components/navbar.js, client/components/singleProduct.js, client/components/user-home.js, client/routes.js, client/store/cart.js, client/store/catalog.js, client/store/index.js, client/store/singleProduct.js, public/style.css, script/helperFuncs.js, server/api/cart.js, server/api/index.js, server/api/product.js, server/db/models/index.js, server/db/models/product.js, server/db/models/review.js
Products:
- ~~Must have title, description, price, and inventory quantity~~
- Must belong to at least one category
- ~~If there is no photo, there must be a placeholder photo used~~
Users:
- ~~Users must have a valid email address~~
- ~~Users email must be unique~~
Order
- Orders must belong to a user OR guest session (authenticated vs unauthenticated)
- Orders must contain line items that capture the price, current product ID and quantity
- If a user completes an order, that order should keep the price of the item at the time when they checked out even if the price of the product later changes
Reviews
- All reviews must belong to a product
- All reviews must belong to a user
- ~~All reviews must be at least X characters~~
=> Data validations

client/components/navbar.js
=> Add change to slogan to be less triggering

server/db/models/address.js
---
Address db model now has a default boolean and no longer has a "BOTH" type.
=> updated address route

.travis.yml, script/seed.spec.js
Changing DB test name for Travis CI tool
=> changing DB name

.travis.yml
How Continuous Integration  && Continuous Deployment work?
1. Dev pushes the code to master
2. Travis, a service running on the cloud"  detects a new commit on master and:
- fetches the code from repo, switches to master
- runs unit tests
3. If all Unit tests OK, Travis deploys app on Heroku (production environment)
=> Travis-Heroku integration

server/api/cart.js
=> updated cart api route for authed users

server/api/users.js, server/db/models/user.js
---
Updated user model and then started an API route for addresses
=> User address pull

server/auth/index.js
---
Giving unauthed users some love and persisting their cart when they login or sign up.
=> convert unauthenticated user cart to CartItems on signup/login

server/api/cart.js
---
Quick validation on api route to make sure that item isn't already in cart
=> cart validating before adding new items

package-lock.json, package.json, public/index.html
=> added semantic ui css

package-lock.json, package.json
=> fixed npm package issue(MERGE THIS FIRST)

package-lock.json, server/api/helpers.js, server/api/users.js, server/api/users.spec.js, server/db/models/user.js
---
Quick change to the user model and then created a validation within the helpers.js file and used it on the Users route.
=> Admin validation

client/components/addReview.js, client/components/singleProduct.js, client/components/singleReview.js
=> Put Semantic styling on single Product, add review, and edit review compoennt

script/seed.js, server/db/models/cart_item.js, server/db/models/index.js
=> Add seed and db changes

server/api/cart.js
=> Add change to cart fetch

client/components/checkout.js, client/components/checkoutForm.js, script/seed.js, server/api/order.js, server/db/models/cart_item.js, server/db/models/index.js
=> Checkout comp

client/components/catalog.js, client/components/sidebar.js
---
Incredible abuses of power inbound!
=> this works

client/components/navbar.js
=> still works

client/components/sidebar.js
=> sorting is nice too

public/style.css, server/api/orderItem.js, server/db/models/order_item.js
Reverts Team-Grapefruit-1909/Grace-Shopper#62
=> Revert "useability changes"

server/api/orderItem.js, server/db/models/index.js
=> getting rid of orderitem references

client/components/catalog.js, client/components/sidebar.js, package-lock.json, package.json, public/style.css
=> Sidebar styling

.travis.yml
=> app name change

client/index.js, cypress.json, cypress/fixtures/credentials.json, cypress/fixtures/products_0_15.json, cypress/integration/homepage.spec.js, cypress/integration/login.spec.js, cypress/integration/shoppingCart.spec.js, cypress/integration/singleProduct.spec.js, cypress/plugins/index.js, cypress/support/commands.js, cypress/support/index.js, package-lock.json, package.json
Hi Guys!
Hope you are doing well
Decided to make green my Github commit heat map 
and started to play around a new JavaScript testing framework "Cypress"
Would be glad if you could hit "Approve" button ;)
=> Introducing cypress tests

.travis.yml
=> heroku app name change
